development:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI') %>
      options:
        server_selection_timeout: 8

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI').sub('/mysms?', '/mysms_test?') %>
      options:
        server_selection_timeout: 8

production:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI') %>
      options:
        server_selection_timeout: 8
